<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="5IE2Y60SLY0XSOP" name="day06.time" tests="1" failures="0" timestamp="2 Jan 2019 03:08:30 GMT" time="2.012" errors="1">
  <testcase name="dd" time="2.012" classname="day06.time">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.dd() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.dd() didn't finish within the time-out 2000
	at java.util.concurrent.ThreadPoolExecutor.tryTerminate(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- dd -->
</testsuite> <!-- day06.time -->
